/** @type {import('tailwindcss').Config} */
module.exports = {
    mode: 'jit',
    content: [
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './src/**/*.{js,ts,jsx,tsx,mdx}',
    ],
    theme: {
        extend: {
            colors: {
                white: '#fff',
                black: '#000',
                gray: {
                    DEFAULT: '#8e8e8e',
                    5: '#f8f8f8',
                    10: '#f0f0f0',
                    20: '#e4e4e4',
                    30: '#d8d8d8',
                    40: '#c6c6c6',
                    60: '#717171',
                    70: '#555555',
                    80: '#2d2d2d',
                    90: '#1d1d1d',
                    100: '#000',
                },
                primary: {
                    DEFAULT: '#246beb',
                    5: '#eff5ff',
                    10: '#d3e1fb',
                    20: '#a7c4f7',
                    30: '#7ca6f3',
                    40: '#5089ef',
                    60: '#1d56bc',
                    70: '#16408d',
                    80: '#0e2b5e',
                    90: '#07152f',
                    100: '#000000',
                },
                secondary: {
                    DEFAULT: '#003675',
                    5: '#edf1f5',
                    10: '#cdd7e4',
                    20: '#b4c4d6',
                    30: '#99b0cb',
                    40: '#2a5c96',
                    60: '#002b5e',
                    70: '#002046',
                    80: '#00162f',
                    90: '#000b17',
                    100: '#000000',
                },
                point: {
                    DEFAULT: '#e71825',
                    5: '#fdf2f3',
                    10: '#fad1d3',
                    20: '#f5a3a8',
                    30: '#f1747c',
                    40: '#ec4651',
                    60: '#b9131e',
                    70: '#8b0e16',
                    80: '#5c0a0f',
                    90: '#2e0507',
                    100: '#000000',
                },
                danger: '#eb003b',
                warning: '#ffb724',
                success: '#008a1e',
                information: '#2768ff',
            },
            fontFamily: {
                base: ['Pretendard GOV', 'sans-serif'],
            },
            fontSize: {
                root: '62.5%',
                'display-sm': '4rem',
                'display-md': '5rem',
                'display-lg': '6.6rem',
                'heading-sm': '3.2rem',
                'heading-md': '4rem',
                'heading-lg': '5rem',
                'title-xsm': '1.5rem',
                'title-sm': '1.7rem',
                'title-md': '1.9rem',
                'title-lg': '2.1rem',
                'title-xlg': '2.5rem',
                'title-xxlg': '3.2rem',
                'body-sm': '1.5rem',
                'body-md': '1.7rem',
                'body-lg': '1.9rem',
                'link-sm': '1.5rem',
                'link-md': '1.7rem',
                'link-lg': '1.9rem',
                'detail-sm': '1.3rem',
                'detail-md': '1.5rem',
                'detail-lg': '1.7rem',
                'label-xsm': '1.3rem',
                'label-sm': '1.5rem',
                'label-md': '1.7rem',
                'label-lg': '1.9rem',
            },
            fontWeight: {
                light: 300,
                normal: 400,
                medium: 500,
                bold: 700,
                bolder: 800,
            },
            lineHeight: {
                none: 1,
                base: 1.5,
            },
            borderRadius: {
                1: '.2rem',
                2: '.4rem',
                3: '.6rem',
                4: '.8rem',
                5: '1.2rem',
                6: '1.6rem',
                7: '2rem',
                8: '2.4rem',
                9: '4rem',
            },
            spacing: {
                0: '0',
                1: '0.2rem',
                2: '0.4rem',
                3: '0.8rem',
                4: '1.2rem',
                5: '1.6rem',
                6: '2rem',
                7: '2.4rem',
                8: '3.2rem',
                9: '4rem',
                10: '4.8rem',
                11: '5.6rem',
                12: '6.4rem',
                13: '7.2rem',
                14: '8rem',
                15: '8.8rem',
                16: '9.6rem',
                17: '10.4rem',
                18: '11.2rem',
                19: '12rem',
                20: '12.8rem',
                21: '13.6rem',
                22: '14.4rem',
                23: '15.2rem',
                24: '16rem',
                25: '16.8rem',
                26: '17.6rem',
                27: '18.4rem',
                28: '19.2rem',
                29: '20rem',
                30: '20.8rem',
                31: '21.6rem',
                32: '22.4rem',
                33: '23.2rem',
                34: '24rem',
                35: '24.8rem',
                36: '25.6rem',
                37: '26.4rem',
                38: '27.2rem',
                39: '28rem',
                40: '28.8rem',
                41: '29.6rem',
                42: '30.4rem',
                43: '31.2rem',
                44: '32rem',
                45: '32.8rem',
                46: '33.6rem',
                47: '34.4rem',
                48: '35.2rem',
                49: '36rem',
                50: '36.8rem',
            },
            screens: {
                sm: '600px',
                md: '1024px',
                lg: '1920px',
                mobile: { max: '599px' },
                mobileMore: { min: '600px' },
                tablet: { min: '600px', max: '1023px' },
                tabletLess: { max: '1023px' },
                tabletMore: { min: '1024px' },
                desktop: { min: '1920px' },
            },
            boxShadow: {
                base: '2px 2px 2px 0px rgba(0, 0, 0, 0.15)',
            },
            transitionProperty: {
                base: 'all 0.4s ease-in-out',
                fade: 'opacity 0.4s linear',
                collapse: 'max-height 0.4s ease',
                collapseWidth: 'width 0.4s ease',
            },
        },
    },
    plugins: [
        function ({ addUtilities }) {
            const newUtilities = {
                // focus mixin
                '.focus-primary': {
                    outlineOffset: '-0.4rem',
                    outline: '2px solid rgba(36, 107, 235, 0.8)', // 예시: primary 색상
                },
                // flex-size mixin
                '.flex-grow-0': {
                    flexGrow: '0',
                },
                '.flex-grow-1': {
                    flexGrow: '1',
                },
                '.flex-shrink-0': {
                    flexShrink: '0',
                },
                '.flex-shrink-1': {
                    flexShrink: '1',
                },
                // btn-reset mixin
                '.btn-reset': {
                    color: 'inherit',
                    border: '0',
                    backgroundColor: 'inherit',
                    '&:hover, &:active': {
                        backgroundColor: 'inherit',
                    },
                },
                // ellipsis mixin
                '.ellipsis-1': {
                    display: '-webkit-box',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    WebkitBoxOrient: 'vertical',
                    WebkitLineClamp: '1',
                },
                '.ellipsis-2': {
                    display: '-webkit-box',
                    overflow: 'hidden',
                    textOverflow: 'ellipsis',
                    WebkitBoxOrient: 'vertical',
                    WebkitLineClamp: '2',
                },
                // sr-only mixin
                '.sr-only': {
                    position: 'absolute !important',
                    width: '1px !important',
                    height: '1px !important',
                    padding: '0 !important',
                    margin: '-1px !important',
                    overflow: 'hidden !important',
                    clip: 'rect(0, 0, 0, 0) !important',
                    whiteSpace: 'nowrap !important',
                    border: '0 !important',
                },
            };
            addUtilities(newUtilities, ['responsive', 'hover', 'focus']);
        },
    ],
};
